### ISSUE TITLE
npm run test not working 

### ISSUE THREAD

**Issue by BenjazEth** [osmlab/osm-community-index#317]
### {
  "type": "Feature",
  "id": "akaki",
  "properties": {},
  "geometry": {
    "type": "Polygon",
    "coordinates": [
      [
        [38.80302, 8.89203],
        [38.80877, 8.89643],
        [38.81538, 8.8849],
        [38.81345, 8.88147],
        [38.81036, 8.88147],
        [38.80672, 8.88461],
        [38.80302, 8.89203]
      ]
    ]
  }
}
###Join our group here:  https://t.me/openstreetmapethiopia

### ET

[error.txt](https://github.com/osmlab/osm-community-index/files/4012295/error.txt)

**Comment by bhousel** [comment]
> ¦??¦  Features: Warning - small area (1.22 km?).  Use a point `includeLocation` instead.
>  C:/Users/BEN10/Desktop/OpenStreetMap_Ethiopia/osm-community-index/features/africa/ethiopia/akaki.geojson

This one is a warning.. It's saying that because the location is so small, you can just specify a center point instead of including a whole wasteful geojson file. (I'd put the point here:  [38.8092, 8.8890] )


> Resources: ¦??¦??¦??Error - Schema validation:
>  C:/Users/BEN10/Desktop/OpenStreetMap_Ethiopia/osm-community-index/resources/africa/ethiopia/aastu.json:
>  instance.id does not match pattern "^[-_.A-Za-z0-9]+$"

This is the actual error.  The build is not happy about the id for some reason.  (If you submit a pull request, I can look at the actual code and see exactly what the issue is.)
