### ISSUE TITLE
Run community index locally

### ISSUE THREAD

**Issue by kmpoppe** [osmlab/osm-community-index#433]
Hi all!

I wanted to test a change I made - which runs perfectly through `npm run test` but I would LOVE to be able to see the impact my changes have.

There is no `npm serve` and I cannot for the life of me figure out how to get on from here.

Any help would be appreciated!

^K

**Comment by kmpoppe** [comment]
Never mind, found that I can publish /docs to my own gh-pages environment, that way I can test what I wanted to test.

**Comment by bhousel** [comment]
Hey @kmpoppe sorry I didn't respond earlier. There isn't a great way to test the file locally but it sounds like you figured it out.

You can replace the `dataURL` line in index.html to point to another file instead of having it fetch the latest featureCollection pushed to the `main` branch.

https://github.com/osmlab/osm-community-index/blob/d67667e062188d0db6a7bad4edb634bea1780a22/docs/index.html#L73-L75

I could definitely make this easier with an `npm serve` command if you want to do this more?  Let me know if you want this reopened.

**Comment by kmpoppe** [comment]
Hi @bhousel and thanks for welcoming me :-) After having figured out the way over gh-pages I was able to understand that the locationSet can be used without explicitly creating a .geoJSON in /resources. 

I just installed `npm http-server` - which works perfectly when serving /docs with the dataURL. Essentially, I now just have to create a .gitignored /docs that uses a local dataURL so that I can only push the change of any feature.

And yes, there's so much to do ... #423 has a whole bunch of things one could care for :)

Question though: I use Windows and have to change .eslint so that the `npm run test` doesn't complain about line breaks. What line break format do I have to keep in the feature-file? LF or CRLF?

Thanks for your great work!

^Kai
