### ISSUE TITLE
Release 5.x: Use of resolveString function

### ISSUE THREAD

**Issue by jbelien** [osmlab/osm-community-index#472]
Spent a few hours now to try to figure out how to import correctly the `resolveString` function in my "OpenStreetMap Community Index viewer" (https://github.com/jbelien/oci-viewer) but can't figure out how to get pass the following error:

```
Error [ERR_PACKAGE_PATH_NOT_EXPORTED]: Package subpath './lib/resolve_strings' is not defined by "exports" in /home/jbelien/github/oci-viewer/node_modules/osm-community-index/package.json imported from /home/jbelien/github/oci-viewer/scripts/build-resource.js
```

Any idea how I can import and use the `resolveString` function from the `lib/` folder ?

Thanks :)

**Comment by bhousel** [comment]
Sure!  You should be able to use a similar code as how this test looks:
https://github.com/osmlab/osm-community-index/blob/main/tests/resolve_strings.test.js

JavaScript is going through some stuff currently, so this is unfortunately more complicated than it should be:

### ES Modules (in Node)
If your JavaScript project is set up for `"type": "module"`, (or if your JavaScript file has an `.mjs` file extension) you can use an ESM import:
```js
import { resolveStrings } from 'osm-community-index';
import defaultsJSON from 'osm-community-index/dist/defaults.json';
const defaults = defaultsJSON.defaults;
…
const resolved = resolveStrings(someItem, defaults);
```
There is a caveat with the above - you can't today import a json file, unless you enable the "experimental JSON modules feature. Create a `.npmrc` file that contains the following line:  `node-options="--no-warnings --experimental-json-modules"
`

### CommonJS (in Node)
Otherwise, your JavaScript project defaults to `"type": "commonjs"`, (or your JavaScript file has a `.cjs` file extension) you can use a CJS import:
```js
const resolveStrings = require('osm-community-index').resolveStrings;
const defaultsJSON = require('osm-community-index/dist/defaults.json');
const defaults = defaultsJSON.defaults;
…
const resolved = resolveStrings(someItem, defaults);
```

### In a browser
Neither of these approaches work in a web browser, so I made a ["IIFE"](https://esbuild.github.io/api/#format-iife) build of the code that _will_ work in a browser. When you load this file in a `<script>` tag, you'll get a `oci` global to use elsewhere in your scripts:
```html
<head>
<script src="https://cdn.jsdelivr.net/npm/osm-community-index@5/dist/javascript/oci.iife.min.js"></script>
</head>
…
<script>
  // get defaults.json somehow
  let defaults = {};
  fetch('https://cdn.jsdelivr.net/npm/osm-community-index@5/dist/defaults.min.json')
    .then(response => {
      if (!response.ok) throw new Error(response.status + ' ' + response.statusText);
      return response.json();
    })
    .then(defaultsJSON => defaults = defaultsJSON.defaults);

  …
  const resolved = oci.resolveStrings(someItem, defaults);
</script>
```

(If any of this advice doesn't work, let me know - I'm guessing and didn't try any of it).

**Comment by jbelien** [comment]
Awesome ! Thanks a lot for this long and detailed explanation @bhousel ! :)

I'll give it another try 🚀

**Comment by jbelien** [comment]
Works like a charm ! 👌 

The trick was indeed [`build.mjs`](https://github.com/jbelien/oci-viewer/blob/master/build.mjs). Thanks again @bhousel !

For a reason that I can't explain I have to use import from ´./node_modules/osm-community-index´ ; import from `osm-community-index` doesn't work.

Long story short, https://community.osm.be/ is now upgraded to OpenStreetMap Community Index v5 ! 🚀
