### ISSUE TITLE
Add OSM Matrix space

### ISSUE THREAD

**Issue by vranki** [osmlab/osm-community-index#485]
## Community Resource Name

OpenStreetMap Matrix Space

### What is it?

Matrix space with all known OSM Matrix (and IRC) rooms

### URL link to the resource

https://matrix.to/#/!dVTUnmFeNhukpAwMoy:t2bot.io?via=matrix.org&via=grin.hu&via=mozilla.org

### Location

Global

### Description (optional)

Matrix is more modern replacement for IRC but still interoperable with it. This space contains
all known OSM related rooms including IRC channels.

**Comment by bhousel** [comment]
Hey @vranki - occasionally we get requests like this to add a worldwide matrix, see #305 / #316, and in the past I've said "no" because it's a global source that would be presented to everyone, but not run by the OSM Foundation.  

I'm ok if local communities want to use matrix to organize and bridge their channels, and I've accepted plenty of these, but for global resources the request really needs to come from the OSMF or CWG.

**Comment by vranki** [comment]
Thanks @bhousel - I understand the situation. What would be the way to approach OSM Foundation to recognize the space and make it official? Looking at big picture Matrix has replaced IRC in major FOSS institutions (KDE, Gnome, Mozilla, Ansible, etc) so it's a logical choice for OSM community in future. 

Currently there are a lot of overlapping OSM chat channels, so as a newcomer it is very confusing. Standardizing to one (open) platform and pointing users to it in documentation would fix this. Naturally bridges can be set up so those who want to stay on other platforms can do so.
