### ISSUE TITLE
adding an additional type

### ISSUE THREAD

**Issue by gplv2** [osmlab/osm-community-index#49]
Can type be expanded to the non-commercial equivalent of slack ?   aka, matrix / riot .

It would probably be better to make it a more generic description like 'webchat' instead of brand names unless it's deliberately used like that somewhere for a reason I'm not aware of.

**Comment by bhousel** [comment]
Sure, if you have a community that uses something else, just ask and I'll add it..  Only requirement is that it needs to be something that a newbie can drop into.

I'm deliberately including branded types because 1. they can have signup quirks (slack is a good example) and 2. to be able to show pretty icons.

**Comment by gplv2** [comment]
Oh, in that sense it's a good idea indeed.  I've made a pull request with our Belgian information in it, so we need to fix that at some poiint, before or after you add a new type.  I could just add another commit to the pull request and change the word now or if you prefer we can wait .  Tx for quick reply.   this is a good idea to gather resources

**Comment by bhousel** [comment]
I've added "matrix" and "discord"

The "matrix" type will have a [generic comments icon](https://fontawesome.com/icons/comments?style=solid) (same icon we use for "forum").  But we can switch it later if Font Awesome ever adds the requested Riot chat icon https://github.com/FortAwesome/Font-Awesome/issues/11270

**Comment by gplv2** [comment]
Thanks !
