### ISSUE TITLE
Discourse local communities

### ISSUE THREAD

**Issue by kmpoppe** [osmlab/osm-community-index#580]
https://community.openstreetmap.org/c/communities/9/none lists local communities that (presumably) will replace forum.openstreetmap.org - there is already a link to the Discourse on the index, but not directly to any special communities.

LATAM and Thailand already are on the index, do you want to add the newly existing (with Austria being the newest one) in a batch by any of the two of us or would you want to have a request from any community by themselves?

**Comment by bhousel** [comment]
I think the idea from https://community.openstreetmap.org/t/community-index-and-new-community-categories-here/2458 is that the local community leaders can make the request once they are ready to accommodate more users.

**Comment by kmpoppe** [comment]
Ok.

**Comment by eisams** [comment]
The old forums are now closed for new posts, so maybe it's best to just do it centrally?

E.g., Norway is missing

**Comment by bhousel** [comment]
> The old forums are now closed for new posts, so maybe it's best to just do it centrally?

I agree, I think it's best to just remove all the old forums since they are readonly and officially deprecated now as of November 2022.

**Comment by eisams** [comment]
I'm opening a discussion on this at the community forums, because I have observed that a few active community forums that I pinged about this one year ago has not updated the index, maybe because they're JOSM users and not aware how prominent this is for iD users :)

If the most common communication channel is not listed there for new users, there's less chance they become active contributors

https://community.openstreetmap.org/t/add-all-community-forums-to-the-community-index/119315
